package com.ufide.proyectofinal;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Alquiler_frm extends javax.swing.JDialog {

    public static ListaVehiculos lista_vehiculos = new ListaVehiculos();
    public static Configuracion config=new Configuracion();
    public static ManejoArchivos manArch=new  ManejoArchivos();
    public static DefaultTableModel modeloTabla = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int col){
            return false;
        }
    };

    /**
     * Creates new form Vehi
     */
    public Alquiler_frm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        manArch.crearArchivos(config.getCarpeta()+config.getArchivoVehiculos());
        llenarListaVehiculos();
        iniciarTablaVehiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        annio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numeroPlaca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cilindrada = new javax.swing.JTextField();
        tipoCombustible = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        capacidadPasajeros = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        precioAlquierXDia = new javax.swing.JTextField();
        arranqueSinLLave = new javax.swing.JCheckBox();
        cargadorInalambrico = new javax.swing.JCheckBox();
        navegadorTraffico = new javax.swing.JCheckBox();
        sensores = new javax.swing.JCheckBox();
        camaraTrasera = new javax.swing.JCheckBox();
        wifi = new javax.swing.JCheckBox();
        monitoreoSatelital = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPlacaVehiculo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCedulaArrendatario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNombreArrendatario = new javax.swing.JTextField();
        txtNumeroSolicitud = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPrecioAlquilerPorDia = new javax.swing.JTextField();
        btnLimp = new javax.swing.JButton();
        btnGuard = new javax.swing.JButton();
        cbxCategoria = new javax.swing.JComboBox<>();
        calFechaAlquiler = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        txtCantidadDiasAlquiler = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        txtTotalAPagar = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabDatos = new javax.swing.JTable();
        btnResetear = new javax.swing.JButton();
        btnDevolverVehiculo = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de Ingreso- Vehiculos"));

        jLabel2.setText("Numero de placa:");

        jLabel3.setText("Marca:");

        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });

        jLabel4.setText("Modelo:");

        jLabel5.setText("Año:");

        jLabel6.setText("Color:");

        jLabel7.setText("Cilindrada:");

        numeroPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroPlacaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de Combustible:");

        cilindrada.setToolTipText("");

        jLabel9.setText("Capacidad de Pasajero: ");

        jLabel10.setText("Precio de Alquiler: ");

        jLabel11.setText("Estado:");

        arranqueSinLLave.setText("Arranca Sin LLave: ");

        cargadorInalambrico.setText("Cargador Inalambrico: ");

        navegadorTraffico.setText("Navegador Trafico:");

        sensores.setText("Sensores:");

        camaraTrasera.setText("Camara Trasera:");

        wifi.setText("Wifi:");

        monitoreoSatelital.setText("Monitoreo Satelital: ");

        jLabel16.setText("Extras: ");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(arranqueSinLLave, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cargadorInalambrico, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(navegadorTraffico, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sensores, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(camaraTrasera, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(wifi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(monitoreoSatelital, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(39, 39, 39)
                                .addComponent(btnLimpiar)))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(24, 24, 24))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(76, 76, 76))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(95, 95, 95)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tipoCombustible, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numeroPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(marca, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(modelo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(annio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(color, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cilindrada, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(capacidadPasajeros)
                                        .addComponent(precioAlquierXDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel16)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioAlquierXDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arranqueSinLLave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargadorInalambrico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navegadorTraffico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sensores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camaraTrasera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wifi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monitoreoSatelital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de Ingreso- Alquileres"));

        jLabel12.setText("Numero Solicitud");

        jLabel13.setText("Fecha Alquiler");

        jLabel14.setText("Placa vehiculo asignado");

        jLabel15.setText("Cedula arrendatario ");

        jLabel17.setText("nombre arrendatario");

        jLabel19.setText("Categoria");

        jLabel20.setText("Precio Alq. x día");

        btnLimp.setText("Limpiar");
        btnLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpActionPerformed(evt);
            }
        });

        btnGuard.setText("Guardar");
        btnGuard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardActionPerformed(evt);
            }
        });

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Super", "Regular", "Diesel" }));

        jLabel24.setText("Cantidad días");

        jLabel25.setText("IVA");

        jLabel26.setText("Total a pagar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalAPagar)
                            .addComponent(txtIVA)
                            .addComponent(txtCantidadDiasAlquiler)
                            .addComponent(txtPrecioAlquilerPorDia)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel19))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNumeroSolicitud, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedulaArrendatario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreArrendatario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calFechaAlquiler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addComponent(btnGuard))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnLimp)
                                        .addGap(135, 135, 135)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(calFechaAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaArrendatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArrendatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioAlquilerPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadDiasAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimp)
                    .addComponent(btnGuard))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta y edición de Alquileres"));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        TabDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabDatos);

        btnResetear.setText("Resetear vista");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });

        btnDevolverVehiculo.setText("Devolver Vehiculo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetear)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(btnDevolverVehiculo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnResetear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolverVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void llenarListaVehiculos(){
        lista_vehiculos= manArch.leerArchivoVehiculos(config.getCarpeta()+
                config.getArchivoVehiculos());
    }
    
    public void llenarTablaVehiculos() {
        String auxArranque, auxCargador, auxNavegador, auxSensor, auxCamara, 
                auxWifi, auxMonitor;
        
        for (NodoVehiculos vehiculo : lista_vehiculos.listaVehiculos()) {
            if(vehiculo.getVehiculo().isArranqueSinLLave()){
                auxArranque="X";
            }else{
                auxArranque="";
            }
            if(vehiculo.getVehiculo().isCargadorInalambrico()){
                auxCargador="X";
            }else{
                auxCargador="";
            }
            if(vehiculo.getVehiculo().isNavegadorTraffico()){
                auxNavegador="X";
            }else{
                auxNavegador="";
            }
            if(vehiculo.getVehiculo().isSensores()){
                auxSensor="X";
            }else{
                auxSensor="";
            }
            if(vehiculo.getVehiculo().isCamaraTrasera()){
                auxCamara="X";
            }else{
                auxCamara="";
            }
            if(vehiculo.getVehiculo().isWifi()){
                auxWifi="X";
            }else{
                auxWifi="";
            }
            if(vehiculo.getVehiculo().isMonitoreoSatelital()){
                auxMonitor="X";
            }else{
                auxMonitor="";
            }

            modeloTabla.addRow(new Object[]{
                vehiculo.getVehiculo().getNumeroPlaca(),
                vehiculo.getVehiculo().getMarca(),
                vehiculo.getVehiculo().getModelo(),
                vehiculo.getVehiculo().getAnnio(),
                vehiculo.getVehiculo().getColor(),
                vehiculo.getVehiculo().getCilindrada(),
                vehiculo.getVehiculo().getTipoCombustible(),
                vehiculo.getVehiculo().getCapacidadPasajeros(),
                vehiculo.getVehiculo().getPrecioAlquierXDia(),
                vehiculo.getVehiculo().getEstado(),
                auxArranque,
                auxCargador,
                auxNavegador,
                auxSensor,
                auxCamara,
                auxWifi,
                auxMonitor});
        }
    }
    
    public void llenarTablaVehiculosBusqueda(Vehiculos vehiculo) {
        String auxArranque, auxCargador, auxNavegador, auxSensor, auxCamara, 
                auxWifi, auxMonitor;
                
        if(vehiculo.isArranqueSinLLave()){
            auxArranque="X";
        }else{
            auxArranque="";
        }
        if(vehiculo.isCargadorInalambrico()){
            auxCargador="X";
        }else{
            auxCargador="";
        }
        if(vehiculo.isNavegadorTraffico()){
            auxNavegador="X";
        }else{
            auxNavegador="";
        }
        if(vehiculo.isSensores()){
            auxSensor="X";
        }else{
            auxSensor="";
        }
        if(vehiculo.isCamaraTrasera()){
            auxCamara="X";
        }else{
            auxCamara="";
        }
        if(vehiculo.isWifi()){
            auxWifi="X";
        }else{
            auxWifi="";
        }
        if(vehiculo.isMonitoreoSatelital()){
            auxMonitor="X";
        }else{
            auxMonitor="";
        }

        modeloTabla.addRow(new Object[]{
            vehiculo.getNumeroPlaca(),
            vehiculo.getMarca(),
            vehiculo.getModelo(),
            vehiculo.getAnnio(),
            vehiculo.getColor(),
            vehiculo.getCilindrada(),
            vehiculo.getTipoCombustible(),
            vehiculo.getCapacidadPasajeros(),
            vehiculo.getPrecioAlquierXDia(),
            vehiculo.getEstado(),
            auxArranque,
            auxCargador,
            auxNavegador,
            auxSensor,
            auxCamara,
            auxWifi,
            auxMonitor});
        
    }

    public void iniciarTablaVehiculos() {
        modeloTabla.addColumn("Placa");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Modelo");
        modeloTabla.addColumn("Año");
        modeloTabla.addColumn("Color");
        modeloTabla.addColumn("Cilindrada");
        modeloTabla.addColumn("Combustible");
        modeloTabla.addColumn("Cap. Pasajeros");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Estado");
        modeloTabla.addColumn("Arr.S.Llave");
        modeloTabla.addColumn("Carg.Inal");
        modeloTabla.addColumn("Nav.GPS");
        modeloTabla.addColumn("Sensores");
        modeloTabla.addColumn("Cam.Trasera");
        modeloTabla.addColumn("Wifi");
        modeloTabla.addColumn("Mon.Sat.");

        TabDatos.setModel(modeloTabla);
        llenarTablaVehiculos();

    }
    
    public void vaciarTablaVehiculos(){
        for (int i = modeloTabla.getRowCount() - 1; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    public void resetearTablaVehiculos() {
        for (int i = modeloTabla.getRowCount() - 1; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
        llenarTablaVehiculos();
    }
    
    public void llenar_cajas(){
        this.txtNumeroSolicitud.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 0).toString());
        this.txtMarca.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 1).toString());
        this.txtPlacaVehiculo.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 2).toString());
        this.txtCedulaArrendatario.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 3).toString());
        this.txtNombreArrendatario.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 4).toString());
        this.txtCilindrada.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 5).toString());
        this.cbxCategoria.setSelectedItem(TabDatos.getValueAt(TabDatos.getSelectedRow(), 6).toString());
        this.txtPrecioAlquilerPorDia.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 7).toString());
        this.txtPrecioAlquiler.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 8).toString());
        this.cbxEstado.setSelectedItem(TabDatos.getValueAt(TabDatos.getSelectedRow(), 9).toString());
       
        if(TabDatos.getValueAt(TabDatos.getSelectedRow(), 10).toString().equals("X")){
            this.cbxArranqueSinLLave.setSelected(true);
        }else{
            this.cbxArranqueSinLLave.setSelected(false);
        }
        if(TabDatos.getValueAt(TabDatos.getSelectedRow(), 11).toString().equals("X")){
            this.cbxCargadorInalambrico.setSelected(true);
        }else{
            this.cbxCargadorInalambrico.setSelected(false);
        }
        if(TabDatos.getValueAt(TabDatos.getSelectedRow(), 12).toString().equals("X")){
            this.cbxNavegadorTraffico.setSelected(true);
        }else{
            this.cbxNavegadorTraffico.setSelected(false);
        }
        if(TabDatos.getValueAt(TabDatos.getSelectedRow(), 13).toString().equals("X")){
            this.cbxSensores.setSelected(true);
        }else{
            this.cbxSensores.setSelected(false);
        }
        if(TabDatos.getValueAt(TabDatos.getSelectedRow(), 14).toString().equals("X")){
            this.cbxCamaraTrasera.setSelected(true);
        }else{
            this.cbxCamaraTrasera.setSelected(false);
        }
        if(TabDatos.getValueAt(TabDatos.getSelectedRow(), 15).toString().equals("X")){
            this.cbxWifi.setSelected(true);
        }else{
            this.cbxWifi.setSelected(false);
        }
        if(TabDatos.getValueAt(TabDatos.getSelectedRow(), 16).toString().equals("X")){
            this.cbxMonitoreoSatelital.setSelected(true);
        }else{
            this.cbxMonitoreoSatelital.setSelected(false);
        }
    }

    public void limpiar_cajas() {
        this.txtNumeroSolicitud.setText("");
        this.txtMarca.setText("");
        this.txtPlacaVehiculo.setText("");
        this.txtCedulaArrendatario.setText("");
        this.txtNombreArrendatario.setText("");
        this.txtCilindrada.setText("");
        this.cbxCategoria.setSelectedIndex(0);
        this.txtPrecioAlquilerPorDia.setText("");
        this.txtPrecioAlquiler.setText("");
        this.cbxEstado.setSelectedIndex(0);
        this.cbxArranqueSinLLave.setSelected(false);
        this.cbxCargadorInalambrico.setSelected(false);
        this.cbxNavegadorTraffico.setSelected(false);
        this.cbxSensores.setSelected(false);
        this.cbxCamaraTrasera.setSelected(false);
        this.cbxWifi.setSelected(false);
        this.cbxMonitoreoSatelital.setSelected(false);
    }

    public String guardarLinea(Vehiculos vehiculo){
        String texto=
                vehiculo.getNumeroPlaca()+"*"+
                vehiculo.getMarca()+"*"+
                vehiculo.getModelo()+"*"+
                vehiculo.getAnnio()+"*"+
                vehiculo.getColor()+"*"+
                vehiculo.getCilindrada()+"*"+
                vehiculo.getTipoCombustible()+"*"+
                vehiculo.getCapacidadPasajeros()+"*"+
                vehiculo.getPrecioAlquierXDia()+"*"+
                vehiculo.getEstado()+"*"+
                vehiculo.isArranqueSinLLave()+"*"+
                vehiculo.isCargadorInalambrico()+"*"+
                vehiculo.isNavegadorTraffico()+"*"+
                vehiculo.isSensores()+"*"+
                vehiculo.isCamaraTrasera()+"*"+
                vehiculo.isWifi()+"*"+
                vehiculo.isMonitoreoSatelital()+"\n";
                
        return texto;
    }

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaActionPerformed

    private void numeroPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroPlacaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // BOTON ACEPTAR
        ListaVehiculos lista_vehiculos = new ListaVehiculos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Consulta por placa 
        String placa=JOptionPane.showInputDialog("Digite el número de placa");
        
        Vehiculos encontrar= lista_vehiculos.buscar(placa);
        if(encontrar==null){
            JOptionPane.showMessageDialog(null, "No hay coincidencias");
        }else{
            vaciarTablaVehiculos();
            llenarTablaVehiculosBusqueda(encontrar);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String placa=TabDatos.getValueAt(TabDatos.getSelectedRow(), 0).toString();
        
        Vehiculos encontrar= lista_vehiculos.buscar(placa);
        if(encontrar==null){
            JOptionPane.showMessageDialog(null, "No hay placa almacenada");
        }else{
            encontrar.setMarca(txtMarca.getText());
            encontrar.setModelo(txtNumeroSolicitud.getText());
            encontrar.setAnnio(Integer.parseInt(txtCedulaArrendatario.getText()));
            encontrar.setColor(txtNombreArrendatario.getText());
            encontrar.setCilindrada(txtCilindrada.getText());
            encontrar.setTipoCombustible(cbxCategoria.getSelectedItem().toString());
            encontrar.setCapacidadPasajeros(Integer.parseInt(txtPrecioAlquilerPorDia.getText()));
            encontrar.setPrecioAlquierXDia(Double.parseDouble(txtPrecioAlquiler.getText()));
            encontrar.setEstado(cbxEstado.getSelectedItem().toString());
            encontrar.setArranqueSinLLave(cbxArranqueSinLLave.isSelected());
            encontrar.setCargadorInalambrico(cbxCargadorInalambrico.isSelected());
            encontrar.setNavegadorTraffico(cbxNavegadorTraffico.isSelected());
            encontrar.setSensores(cbxSensores.isSelected());
            encontrar.setCamaraTrasera(cbxCamaraTrasera.isSelected());
            encontrar.setWifi(cbxWifi.isSelected());
            encontrar.setMonitoreoSatelital(cbxMonitoreoSatelital.isSelected());
            lista_vehiculos.modifica(encontrar);
            limpiar_cajas();
            vaciarTablaVehiculos();
            llenarTablaVehiculos();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String placa=TabDatos.getValueAt(TabDatos.getSelectedRow(), 0).toString();
        Vehiculos encontrar= lista_vehiculos.buscar(placa);
        lista_vehiculos.elimina(encontrar);
        limpiar_cajas();
        vaciarTablaVehiculos();
        llenarTablaVehiculos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TabDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDatosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            llenar_cajas();
        }
    }//GEN-LAST:event_TabDatosMouseClicked

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        // TODO add your handling code here:
        limpiar_cajas();
        resetearTablaVehiculos();
    }//GEN-LAST:event_btnResetearActionPerformed

    private void btnGuardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardActionPerformed
        // TODO add your handling code here:
        if (txtNumeroSolicitud.getText().isEmpty() == false
            || txtMarca.getText().isEmpty() == false
            || txtPlacaVehiculo.getText().isEmpty() == false
            || txtCedulaArrendatario.getText().isEmpty() == false
            || txtNombreArrendatario.getText().isEmpty() == false
            || txtCilindrada.getText().isEmpty() == false
            || txtPrecioAlquilerPorDia.getText().isEmpty() == false
            || txtPrecioAlquiler.getText().isEmpty() == false){

            Vehiculos vehiculo = new Vehiculos(
                txtNumeroSolicitud.getText(),
                txtMarca.getText(),
                txtPlacaVehiculo.getText(),
                Integer.parseInt(txtCedulaArrendatario.getText()),
                txtNombreArrendatario.getText(),
                txtCilindrada.getText(),
                cbxCategoria.getSelectedItem().toString(),
                Integer.parseInt(txtPrecioAlquilerPorDia.getText()),
                Double.parseDouble(txtPrecioAlquiler.getText()),
                cbxEstado.getSelectedItem().toString(),
                cbxArranqueSinLLave.isSelected(),
                cbxCargadorInalambrico.isSelected(),
                cbxNavegadorTraffico.isSelected(),
                cbxSensores.isSelected(),
                cbxCamaraTrasera.isSelected(),
                cbxWifi.isSelected(),
                cbxMonitoreoSatelital.isSelected()
            );

            lista_vehiculos.inserta(vehiculo);

            manArch.escribirArchivo(config.getCarpeta()+config.getArchivoVehiculos(), guardarLinea(vehiculo));
            resetearTablaVehiculos();
        }
        limpiar_cajas();
    }//GEN-LAST:event_btnGuardActionPerformed

    private void btnLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpActionPerformed
        // Limpia las cajas
        limpiar_cajas();
    }//GEN-LAST:event_btnLimpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alquiler_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alquiler_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alquiler_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alquiler_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Alquiler_frm dialog = new Alquiler_frm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabDatos;
    private javax.swing.JTextField annio;
    private javax.swing.JCheckBox arranqueSinLLave;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDevolverVehiculo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuard;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimp;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnResetear;
    private com.toedter.calendar.JDateChooser calFechaAlquiler;
    private javax.swing.JCheckBox camaraTrasera;
    private javax.swing.JTextField capacidadPasajeros;
    private javax.swing.JCheckBox cargadorInalambrico;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JTextField cilindrada;
    private javax.swing.JTextField color;
    private javax.swing.JTextField estado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JCheckBox monitoreoSatelital;
    private javax.swing.JCheckBox navegadorTraffico;
    private javax.swing.JTextField numeroPlaca;
    private javax.swing.JTextField precioAlquierXDia;
    private javax.swing.JCheckBox sensores;
    private javax.swing.JTextField tipoCombustible;
    private javax.swing.JTextField txtCantidadDiasAlquiler;
    private javax.swing.JTextField txtCedulaArrendatario;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtNombreArrendatario;
    private javax.swing.JTextField txtNumeroSolicitud;
    private javax.swing.JTextField txtPlacaVehiculo;
    private javax.swing.JTextField txtPrecioAlquilerPorDia;
    private javax.swing.JTextField txtTotalAPagar;
    private javax.swing.JCheckBox wifi;
    // End of variables declaration//GEN-END:variables
}
