package Vista;

import Modelo.Configuracion;
import Controlador.ListaVehiculos;
import Controlador.ManejoArchivos;
import Modelo.NodoSolicitud;
import Controlador.PilaSolicitudes;
import Modelo.Clientes;
import Modelo.Solicitudes;
import static Vista.Clientes_frm.modeloTabla;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.ExcelStyleDateFormatter;

/**
 *
 * @author User
 */
public class Solicitudes_frm extends javax.swing.JDialog {

    public static PilaSolicitudes pila_solicitudes = new PilaSolicitudes();
    public static Configuracion config = new Configuracion();
    public static ManejoArchivos manArch = new ManejoArchivos(config.getCarpeta() + config.getArchivo(), 2);
    public static DefaultTableModel modeloTabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };

    public Solicitudes_frm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarListaSolicitudes();
        IniciarTablaSolicitudes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * alwayolicituds regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        annio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numeroPlaca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cilindrada = new javax.swing.JTextField();
        tipoCombustible = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        capacidadPasajeros = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        precioAlquierXDia = new javax.swing.JTextField();
        arranqueSinLLave = new javax.swing.JCheckBox();
        cargadorInalambrico = new javax.swing.JCheckBox();
        navegadorTraffico = new javax.swing.JCheckBox();
        sensores = new javax.swing.JCheckBox();
        camaraTrasera = new javax.swing.JCheckBox();
        wifi = new javax.swing.JCheckBox();
        monitoreoSatelital = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNumeroSolicitud = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCantidadDias = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        cbxArranqueSinLLave = new javax.swing.JCheckBox();
        cbxCargadorInalambrico = new javax.swing.JCheckBox();
        cbxNavegadorTraffico = new javax.swing.JCheckBox();
        cbxSensores = new javax.swing.JCheckBox();
        cbxCamaraTrasera = new javax.swing.JCheckBox();
        cbxWifi = new javax.swing.JCheckBox();
        cbxMonitoreoSatelital = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        btnLimp = new javax.swing.JButton();
        btnGuard = new javax.swing.JButton();
        cbxEstadoSolicitud = new javax.swing.JComboBox<>();
        cbxCategoria = new javax.swing.JComboBox<>();
        calFechaSolicitud = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtannio = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCantMinimaPasajeros = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabDatos = new javax.swing.JTable();
        btnResetear = new javax.swing.JButton();
        btnAlquilar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de Ingreso- Vehiculos"));

        jLabel2.setText("Numero de placa:");

        jLabel3.setText("Marca:");

        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });

        jLabel4.setText("Modelo:");

        jLabel5.setText("Año:");

        jLabel6.setText("Color:");

        jLabel7.setText("Cilindrada:");

        numeroPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroPlacaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de Combustible:");

        cilindrada.setToolTipText("");

        jLabel9.setText("Capacidad de Pasajero: ");

        jLabel10.setText("Precio de Alquiler: ");

        jLabel11.setText("Estado:");

        arranqueSinLLave.setText("Arranca Sin LLave: ");

        cargadorInalambrico.setText("Cargador Inalambrico: ");

        navegadorTraffico.setText("Navegador Trafico:");

        sensores.setText("Sensores:");

        camaraTrasera.setText("Camara Trasera:");

        wifi.setText("Wifi:");

        monitoreoSatelital.setText("Monitoreo Satelital: ");

        jLabel16.setText("Extras: ");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(arranqueSinLLave, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cargadorInalambrico, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(navegadorTraffico, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sensores, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(camaraTrasera, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(wifi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(monitoreoSatelital, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(39, 39, 39)
                                .addComponent(btnLimpiar)))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(24, 24, 24))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(76, 76, 76))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(95, 95, 95)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tipoCombustible, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numeroPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(marca, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(modelo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(annio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(color, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cilindrada, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(capacidadPasajeros)
                                        .addComponent(precioAlquierXDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel16)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioAlquierXDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arranqueSinLLave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargadorInalambrico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navegadorTraffico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sensores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camaraTrasera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wifi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monitoreoSatelital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de Ingreso- Solicitudes"));

        jLabel12.setText("Numero Solicitud");

        jLabel13.setText("Estado");

        jLabel14.setText("Fecha Solicitud");

        jLabel15.setText("Cedula");

        jLabel17.setText("Nombre");

        jLabel18.setText("Categoria");

        jLabel19.setText("Cantidad Dias");

        txtCantidadDias.setToolTipText("");

        jLabel20.setText("Marca");

        cbxArranqueSinLLave.setText("Arranca Sin LLave: ");

        cbxCargadorInalambrico.setText("Cargador Inalambrico: ");

        cbxNavegadorTraffico.setText("Navegador Trafico:");

        cbxSensores.setText("Sensores:");

        cbxCamaraTrasera.setText("Camara Trasera:");

        cbxWifi.setText("Wifi:");

        cbxMonitoreoSatelital.setText("Monitoreo Satelital: ");

        jLabel23.setText("Extras: ");

        btnLimp.setText("Limpiar");
        btnLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpActionPerformed(evt);
            }
        });

        btnGuard.setText("Guardar");
        btnGuard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardActionPerformed(evt);
            }
        });

        cbxEstadoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Usado" }));

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Super", "Regular", "Diesel" }));
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });

        jLabel24.setText("Modelo");

        jLabel25.setText("Año");

        jLabel21.setText("Cant. min. pasajeros");

        txtCantMinimaPasajeros.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnGuard)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel23))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnLimp))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtannio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel21))
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNumeroSolicitud, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxEstadoSolicitud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxCategoria, 0, 126, Short.MAX_VALUE)
                                        .addComponent(txtCantidadDias)
                                        .addComponent(calFechaSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCantMinimaPasajeros)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxArranqueSinLLave, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCargadorInalambrico, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNavegadorTraffico, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCamaraTrasera, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMonitoreoSatelital, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxEstadoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(calFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtCantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCantMinimaPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtannio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxArranqueSinLLave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCargadorInalambrico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxNavegadorTraffico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSensores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCamaraTrasera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxWifi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMonitoreoSatelital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimp)
                    .addComponent(btnGuard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta y edición de Solicitudes"));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        TabDatos.setModel(modeloTabla);
        TabDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabDatos);

        btnResetear.setText("Resetear vista");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });

        btnAlquilar.setText("Alquilar");
        btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilarActionPerformed(evt);
            }
        });

        jButton1.setText("Menú Inicial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetear)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlquilar)
                .addGap(386, 386, 386))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnResetear)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlquilar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarListaSolicitudes() {
        this.pila_solicitudes=manArch.leerArchivoSolicitudes();
        
    }

    public void llenarTablaSolicitudes() {
        String auxArranque, auxCargador, auxNavegador, auxSensor, auxCamara,
                auxWifi, auxMonitor;

        for (NodoSolicitud nodo : PilaSolicitudes.listaSolicitudes()) {
            if (nodo.getSolicitud().isArranqueSinLLave()) {
                auxArranque = "X";
            } else {
                auxArranque = "";
            }
            if (nodo.getSolicitud().isCargadorInalambrico()) {
                auxCargador = "X";
            } else {
                auxCargador = "";
            }
            if (nodo.getSolicitud().isNavegadorTraffico()) {
                auxNavegador = "X";
            } else {
                auxNavegador = "";
            }
            if (nodo.getSolicitud().isSensores()) {
                auxSensor = "X";
            } else {
                auxSensor = "";
            }
            if (nodo.getSolicitud().isCamaraTrasera()) {
                auxCamara = "X";
            } else {
                auxCamara = "";
            }
            if (nodo.getSolicitud().isWifi()) {
                auxWifi = "X";
            } else {
                auxWifi = "";
            }
            if (nodo.getSolicitud().isMonitoreoSatelital()) {
                auxMonitor = "X";
            } else {
                auxMonitor = "";
            }

            modeloTabla.addRow(new Object[]{
                nodo.getSolicitud().getIdSolicitud(),
                nodo.getSolicitud().getEstadoSolicitud(),
                nodo.getSolicitud().getFechaSolicitud(),
                nodo.getSolicitud().getCedula(),
                nodo.getSolicitud().getNombre(),
                nodo.getSolicitud().getCategoria(),
                nodo.getSolicitud().getCantidadDias(),
                nodo.getSolicitud().getCantidadMinimaPasajeros(),
                nodo.getSolicitud().getMarca(),
                nodo.getSolicitud().getModelo(),
                nodo.getSolicitud().getAnnio(),
                auxArranque,
                auxCargador,
                auxNavegador,
                auxSensor,
                auxCamara,
                auxWifi,
                auxMonitor});
        }
    }

    public void llenarTablaSolicitudesBusqueda(NodoSolicitud nodo) {
        String auxArranque, auxCargador, auxNavegador, auxSensor, auxCamara,
                auxWifi, auxMonitor;

        if (nodo.getSolicitud().isArranqueSinLLave()) {
            auxArranque = "X";
        } else {
            auxArranque = "";
        }
        if (nodo.getSolicitud().isCargadorInalambrico()) {
            auxCargador = "X";
        } else {
            auxCargador = "";
        }
        if (nodo.getSolicitud().isNavegadorTraffico()) {
            auxNavegador = "X";
        } else {
            auxNavegador = "";
        }
        if (nodo.getSolicitud().isSensores()) {
            auxSensor = "X";
        } else {
            auxSensor = "";
        }
        if (nodo.getSolicitud().isCamaraTrasera()) {
            auxCamara = "X";
        } else {
            auxCamara = "";
        }
        if (nodo.getSolicitud().isWifi()) {
            auxWifi = "X";
        } else {
            auxWifi = "";
        }
        if (nodo.getSolicitud().isMonitoreoSatelital()) {
            auxMonitor = "X";
        } else {
            auxMonitor = "";
        }

        modeloTabla.addRow(new Object[]{
            nodo.getSolicitud().getIdSolicitud(),
            nodo.getSolicitud().getEstadoSolicitud(),
            nodo.getSolicitud().getFechaSolicitud(),
            nodo.getSolicitud().getCedula(),
            nodo.getSolicitud().getNombre(),
            nodo.getSolicitud().getCategoria(),
            nodo.getSolicitud().getCantidadDias(),
            nodo.getSolicitud().getCantidadMinimaPasajeros(),
            nodo.getSolicitud().getMarca(),
            nodo.getSolicitud().getModelo(),
            nodo.getSolicitud().getAnnio(),
            auxArranque,
            auxCargador,
            auxNavegador,
            auxSensor,
            auxCamara,
            auxWifi,
            auxMonitor});
    }

    public void IniciarTablaSolicitudes() {
        if (modeloTabla.getColumnCount() == 0) {
            modeloTabla.addColumn("Id.Sol");
            modeloTabla.addColumn("Est.Sol");
            modeloTabla.addColumn("Fecha.Sol");
            modeloTabla.addColumn("Cedula");
            modeloTabla.addColumn("Nombre");
            modeloTabla.addColumn("Categoria");
            modeloTabla.addColumn("Cant.dias");
            modeloTabla.addColumn("Cant.Min.P");
            modeloTabla.addColumn("Marca");
            modeloTabla.addColumn("Modelo");
            modeloTabla.addColumn("Año");
            modeloTabla.addColumn("Arranq");
            modeloTabla.addColumn("Carg.Inal");
            modeloTabla.addColumn("Nav.Traf");
            modeloTabla.addColumn("Sensores");
            modeloTabla.addColumn("Cam.Tras");
            modeloTabla.addColumn("Wifi");
            modeloTabla.addColumn("Mon.Sat");
        }
        llenarTablaSolicitudes();

    }

    public void vaciarTablaSolicitudes() {
        for (int i = modeloTabla.getRowCount() - 1; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    public void resetearTablaSolicitudes() {
        for (int i = modeloTabla.getRowCount() - 1; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
        llenarTablaSolicitudes();
    }

    public void llenar_cajas() {
        try {
            this.txtNumeroSolicitud.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 0).toString());
            this.cbxEstadoSolicitud.setSelectedItem(TabDatos.getValueAt(TabDatos.getSelectedRow(), 1).toString());
            SimpleDateFormat format = new ExcelStyleDateFormatter("dd-MM-yyyy");
            Date fechaFormateada = format.parse(TabDatos.getValueAt(TabDatos.getSelectedRow(), 2).toString());
            this.calFechaSolicitud.setDate(fechaFormateada);
            this.txtCedula.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 3).toString());
            this.txtNombre.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 4).toString());
            this.cbxCategoria.setSelectedItem(TabDatos.getValueAt(TabDatos.getSelectedRow(), 5).toString());
            this.txtCantidadDias.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 6).toString());
            this.txtCantMinimaPasajeros.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 7).toString());
            this.txtMarca.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 8).toString());
            this.txtModelo.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 9).toString());
            this.txtannio.setText(TabDatos.getValueAt(TabDatos.getSelectedRow(), 10).toString());
            if (TabDatos.getValueAt(TabDatos.getSelectedRow(), 11).toString().equals("X")) {
                this.cbxArranqueSinLLave.setSelected(true);
            } else {
                this.cbxArranqueSinLLave.setSelected(false);
            }
            if (TabDatos.getValueAt(TabDatos.getSelectedRow(), 12).toString().equals("X")) {
                this.cbxCargadorInalambrico.setSelected(true);
            } else {
                this.cbxCargadorInalambrico.setSelected(false);
            }
            if (TabDatos.getValueAt(TabDatos.getSelectedRow(), 13).toString().equals("X")) {
                this.cbxNavegadorTraffico.setSelected(true);
            } else {
                this.cbxNavegadorTraffico.setSelected(false);
            }
            if (TabDatos.getValueAt(TabDatos.getSelectedRow(), 14).toString().equals("X")) {
                this.cbxSensores.setSelected(true);
            } else {
                this.cbxSensores.setSelected(false);
            }
            if (TabDatos.getValueAt(TabDatos.getSelectedRow(), 15).toString().equals("X")) {
                this.cbxCamaraTrasera.setSelected(true);
            } else {
                this.cbxCamaraTrasera.setSelected(false);
            }
            if (TabDatos.getValueAt(TabDatos.getSelectedRow(), 16).toString().equals("X")) {
                this.cbxWifi.setSelected(true);
            } else {
                this.cbxWifi.setSelected(false);
            }
            if (TabDatos.getValueAt(TabDatos.getSelectedRow(), 17).toString().equals("X")) {
                this.cbxMonitoreoSatelital.setSelected(true);
            } else {
                this.cbxMonitoreoSatelital.setSelected(false);
            }
        } catch (Exception e) {
            System.err.println(e);
        }

    }

    public void limpiar_cajas() {
        this.txtNumeroSolicitud.setText("");
        this.cbxEstadoSolicitud.setSelectedItem("");
        Date today = Calendar.getInstance().getTime();
        this.calFechaSolicitud.setDate(today);
        this.txtCedula.setText("");
        this.txtNombre.setText("");
        this.cbxCategoria.setSelectedItem("");
        this.txtCantidadDias.setText("");
        this.txtCantMinimaPasajeros.setText("");
        this.txtMarca.setText("");
        this.txtModelo.setText("");
        this.txtannio.setText("");
        this.cbxArranqueSinLLave.setSelected(false);
        this.cbxCargadorInalambrico.setSelected(false);
        this.cbxNavegadorTraffico.setSelected(false);
        this.cbxSensores.setSelected(false);
        this.cbxCamaraTrasera.setSelected(false);
        this.cbxWifi.setSelected(false);
        this.cbxMonitoreoSatelital.setSelected(false);

    }


    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaActionPerformed

    private void numeroPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroPlacaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // BOTON ACEPTAR
        ListaVehiculos lista_vehiculos = new ListaVehiculos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Consulta por placa 
        String solicitud = JOptionPane.showInputDialog("Digite el número de solicitud");
        NodoSolicitud encontrar = pila_solicitudes.buscarN_Placa(solicitud);
        if (encontrar == null) {
            JOptionPane.showMessageDialog(null, "No hay coincidencias");
        } else {
            vaciarTablaSolicitudes();
            llenarTablaSolicitudesBusqueda(encontrar);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void TabDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDatosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            llenar_cajas();
        }
    }//GEN-LAST:event_TabDatosMouseClicked

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        // TODO add your handling code here:
        limpiar_cajas();
        resetearTablaSolicitudes();
    }//GEN-LAST:event_btnResetearActionPerformed

    private void btnGuardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat standar = new SimpleDateFormat("dd-MM-yyyy");
        String fecha = standar.format(calFechaSolicitud.getDate());
        if (this.txtNumeroSolicitud.getText().isEmpty() == false
                || this.txtCedula.getText().isEmpty() == false
                || this.txtNombre.getText().isEmpty() == false
                || this.txtCantidadDias.getText().isEmpty() == false
                || this.txtCantMinimaPasajeros.getText().isEmpty() == false
                || this.txtMarca.getText().isEmpty() == false
                || this.txtModelo.getText().isEmpty() == false
                || this.txtannio.getText().isEmpty() == false) {

            Solicitudes solicitud = new Solicitudes(
                    this.txtNumeroSolicitud.getText(),
                    cbxEstadoSolicitud.getSelectedItem().toString(),
                    fecha,
                    Integer.parseInt(this.txtCedula.getText()),
                    this.txtNombre.getText(),
                    cbxCategoria.getSelectedItem().toString(),
                    
                    Integer.parseInt(this.txtCantidadDias.getText()),
                    Integer.parseInt(this.txtCantMinimaPasajeros.getText()),
                    this.txtMarca.getText(),
                    this.txtModelo.getText(),
                    this.txtannio.getText(),
                    cbxArranqueSinLLave.isSelected(),
                    cbxCargadorInalambrico.isSelected(),
                    cbxNavegadorTraffico.isSelected(),
                    cbxSensores.isSelected(),
                    cbxCamaraTrasera.isSelected(),
                    cbxWifi.isSelected(),
                    cbxMonitoreoSatelital.isSelected()
            );
            pila_solicitudes.push(solicitud);
            resetearTablaSolicitudes();
            pila_solicitudes.estado();     
        }
        limpiar_cajas();
    }//GEN-LAST:event_btnGuardActionPerformed

    private void btnLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpActionPerformed
        // Limpia las cajas
        limpiar_cajas();
    }//GEN-LAST:event_btnLimpActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuInicial menu = new MenuInicial();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed
        this.dispose();
        new Alquiler_frm(null, true).show();
    }//GEN-LAST:event_btnAlquilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitudes_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitudes_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitudes_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitudes_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Solicitudes_frm dialog = new Solicitudes_frm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabDatos;
    private javax.swing.JTextField annio;
    private javax.swing.JCheckBox arranqueSinLLave;
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuard;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimp;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnResetear;
    private com.toedter.calendar.JDateChooser calFechaSolicitud;
    private javax.swing.JCheckBox camaraTrasera;
    private javax.swing.JTextField capacidadPasajeros;
    private javax.swing.JCheckBox cargadorInalambrico;
    private javax.swing.JCheckBox cbxArranqueSinLLave;
    private javax.swing.JCheckBox cbxCamaraTrasera;
    private javax.swing.JCheckBox cbxCargadorInalambrico;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxEstadoSolicitud;
    private javax.swing.JCheckBox cbxMonitoreoSatelital;
    private javax.swing.JCheckBox cbxNavegadorTraffico;
    private javax.swing.JCheckBox cbxSensores;
    private javax.swing.JCheckBox cbxWifi;
    private javax.swing.JTextField cilindrada;
    private javax.swing.JTextField color;
    private javax.swing.JTextField estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JCheckBox monitoreoSatelital;
    private javax.swing.JCheckBox navegadorTraffico;
    private javax.swing.JTextField numeroPlaca;
    private javax.swing.JTextField precioAlquierXDia;
    private javax.swing.JCheckBox sensores;
    private javax.swing.JTextField tipoCombustible;
    private javax.swing.JTextField txtCantMinimaPasajeros;
    private javax.swing.JTextField txtCantidadDias;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroSolicitud;
    private javax.swing.JTextField txtannio;
    private javax.swing.JCheckBox wifi;
    // End of variables declaration//GEN-END:variables
}
